p8105_hw2_cl4469
================
Chen Liang
2023-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Peoblem 1

Read and clean the pols-month dataset:

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols_month_df <- read_csv("data1/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE)|>
  mutate(year = as.numeric(year)) |>
  left_join(x = _, y = month_df) |>
  mutate(president = NA,
         president = ifelse(prez_gop == 0 & prez_dem == 1, "dem",
        ifelse(prez_gop == 1 & prez_dem == 0, "gop", NA))) |>
  select(-prez_dem, -prez_gop,-day) |>
  relocate(year,month, president)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

Read and clean the snp dataset:

``` r
snp_df <- read_csv("data1/snp.csv") |>
  janitor::clean_names()|>
  separate(date,
           into=c("day","month","year"),
           sep="/",convert=T) |>
  mutate(year=ifelse(year>50,1900+year, year+2000),
         month=month.name[month]) |>
  select(-day) |>
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Read and clean the unemployment dataset:

``` r
unemployment = 
  read_csv("data1/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

Merging snp_df into pols_month_df, and merging unemp_df into the result

``` r
pols_snp_df=left_join(pols_month_df,snp_df,by=c("year","month"))
data_538=(left_join(pols_snp_df,unemployment,by=c("year","month")))
str(data_538)
```

    ## tibble [1,382 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:1382] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:1382] "January" "February" "March" "April" ...
    ##  $ president   : chr [1:1382] "dem" "dem" "dem" "dem" ...
    ##  $ month_num   : int [1:1382] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:1382] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:1382] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:1382] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:1382] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:1382] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:1382] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ month_abb   : chr [1:1382] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:1382] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:1382] NA NA NA NA NA NA NA NA NA NA ...

## Problem 2

``` r
library(tidyverse)
library(readxl)
```

#### Reading and cleaning the Mr. Trash Wheel sheet:

``` r
trash_path = "data2/202309 Trash Wheel Collection Data.xlsx"
mr_trash = 
  read_excel(
  path = trash_path,
  sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N"))|>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(homes_powered=weight_tons*(500/30),
         name="Mr.",
         year = as.numeric(year)) |>
  relocate(name)
```

Description of mr_trash: The data contains 584 observations and 15
variables. There are several key variables including dumpster number,
date of collection, amount of total litter, types of litter, etc. And a
new `homes_powered` variable is based on the calculation described in
the Homes powered note. Then Converting the character year variable into
a numeric one and adding an additional variable `name` to help with the
final merge of the datasets

#### Reading, cleaning and manipulating Professor Trash Wheel sheets:

``` r
trash_path = "data2/202309 Trash Wheel Collection Data.xlsx"
Prof_df= 
  read_excel(
  path = trash_path,
  sheet = "Professor Trash Wheel",
  range = cell_cols("A:M")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(homes_powered=weight_tons*(500/30),
         name="Prof") |>
  relocate(name)
```

Description of mr_trash: The data contains 106 observations and 14
variables. There are several key variables including dumpster number,
date of collection, amount of total litter, types of litter, etc. And a
new `homes_powered` variable is based on the calculation described in
the Homes powered note. Then adding an additional variable `name` to
help with the final merge of the datasets

#### Reading, cleaning and manipulating Gwynnda sheets:

``` r
trash_path = "data2/202309 Trash Wheel Collection Data.xlsx"
Gwynnda_df= 
  read_excel(
  path = trash_path,
  sheet = "Gwynnda Trash Wheel",
  range = cell_cols("A:K")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(homes_powered=weight_tons*(500/30),
  name="Gwy") |>
  relocate(name)
```

Description of mr_trash: The data contains 106 observations and 14
variables. There are several key variables including dumpster number,
date of collection, amount of total litter, types of litter, etc. And a
new `homes_powered` variable is based on the calculation described in
the Homes powered note. Then adding an additional variable `name` to
help with the final merge of the datasets

#### Combine these with the Mr. Trash Wheel dataset to produce a single tidy dataset

``` r
Total_df =
  bind_rows(Prof_df,Gwynnda_df,mr_trash) |>
  janitor::clean_names()
```

#### calculate the total weight of trash collected by Professor Trash Wheel, and the total number of cigarette butts collected by Gwynnda in July of 2021

``` r
sum(Total_df %>% filter(name == "Prof") %>% select(weight_tons))
```

    ## [1] 216.26

``` r
sum(Total_df %>% filter(name=="Gwy",year==2021, month=="July") %>% select(cigarette_butts))
```

    ## [1] 16300

For the resulting dataset `Total_df`, it has 845 observations and 15
variables and tells us about how much trash in each of their dumpsters
were collected by Mr. Trash Wheel, professor Trash Wheel, and Gwynnda
Trash Wheel between the year of 2017, 2017 to 2017, 2017. In detail, the
dataset have many key variables, such
as`weight_tons`,`volume_cubic_yards`,`homes_powered`. The variable
`weight_tons` measures how much trash were collected, such as
`plastic_bottles`,`polystyrene`,`cigarette_butts`. And the total weight
of trash collected by Professor Trash Wheel is 216.26. At last, In July
2021, the total number of cigarette butts collected by Gwynnda is
1.63^{4}.

## Problem 3

#### Read and clean the baseline_df dataset:

``` r
baseline_df <- read_csv("data3/MCI_baseline.csv", skip=1)|>
  janitor::clean_names() |>
  mutate(sex = ifelse(sex ==1, "Male","Female"),
         apoe4= ifelse(apoe4==1,"Carrier","Non-carrier"),
         age_at_onset=as.numeric(age_at_onset))|>
  filter(current_age < age_at_onset | is.na(age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `age_at_onset = as.numeric(age_at_onset)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

The original dataset `baseline_df`, it has 479 observations and
6variables, which describes the age at the study baseline, sex, years of
education, apoe4 carry status and age at the onset of MCI. First, I
clean and tidy data and use mutate function to change the `sex` and
`apoe4` to non-numeric variable types. Second, I converted the
age_at_onset variable from character to numeric so that the dataset can
be filtered in the next step. At last, If the patients `current_age` is
larger than`age_at_onset`, these participants are not meet the criteria
because they have MCI at baseline, and these observations were removed,
so I filtered to exclude patients who do not have MCI at baseline. After
this process, there are 479 observations left.

``` r
#How many participants were recruited
  nrow(baseline_df)
```

    ## [1] 479

``` r
#of these how many develop MCI
  baseline_clean = baseline_df %>%filter(!is.na(age_at_onset))
  nrow(baseline_clean)
```

    ## [1] 93

``` r
#What is the average baseline age? 
  mean(baseline_df$current_age)
```

    ## [1] 65.0286

``` r
#What proportion of women in the study are APOE4 carriers?
##The number of females:  
  nrow (filter(baseline_df, sex == "Female"))
```

    ## [1] 210

``` r
##The number of females who have apeo4 carrier:
  nrow(filter(baseline_df, sex == "Female" & apoe4 == "Carrier"))
```

    ## [1] 63

``` r
#The ratio
  nrow(filter(baseline_df, sex == "Female" & apoe4 == "Carrier"))/nrow (filter(baseline_df, sex == "Female"))
```

    ## [1] 0.3

For the original dataset `baseline_df`, there are a total of 479
participants recruited. Among this participants, 93 participants develop
MCI.The average age of the patients was 65.0286013 years old. The
dataset contained 210 females. Among these women,
`nrow(filter(baseline_df, sex == "Female" & apoe4 == "Carrier"))` were
carriers. Thus, the proportion of women in the study are APOE4 carriers
is 0.3

``` r
amyloid_df <- read_csv("data3/mci_amyloid.csv",skip=1) |>
  janitor::clean_names()|>
  rename(id = study_id,
         time_0=baseline) |>
  pivot_longer(
    time_0:time_8, 
    names_to = "years_since_baseline",
    values_to = "baseline")
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
anti_join(amyloid_df,baseline_df)
```

    ## Joining with `by = join_by(id)`

    ## # A tibble: 80 × 3
    ##       id years_since_baseline baseline   
    ##    <dbl> <chr>                <chr>      
    ##  1    72 time_0               0.106965463
    ##  2    72 time_2               <NA>       
    ##  3    72 time_4               0.107266218
    ##  4    72 time_6               0.106665207
    ##  5    72 time_8               <NA>       
    ##  6   234 time_0               0.110521689
    ##  7   234 time_2               0.110988335
    ##  8   234 time_4               0.110318671
    ##  9   234 time_6               0.107334344
    ## 10   234 time_8               0.108868811
    ## # ℹ 70 more rows

``` r
baseline=baseline_df |>
anti_join(amyloid_df, by= "id")
nrow(baseline)
```

    ## [1] 8

``` r
amyloid=amyloid_df |>
anti_join(baseline_df, by= "id")
nrow(amyloid)
```

    ## [1] 80

``` r
Combine_df = inner_join(baseline_df, amyloid_df, by = "id")
write.csv(Combine_df, file = "data3/Combine_df.csv")
```
